version: 2.0
jobs:
  getIssues:
    steps:
      - checkout
      - run: npm install
      - run: npm run get-stats

workflows:
  hourly:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - getIssues
